apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: debian
spec:
  hosts:
  - "deb.debian.org"
  - "security.debian.org"
  - "cdn-fastly.deb.debian.org"
  ports:
  - number: 80
    name: http
    protocol: HTTP
  - number: 443
    name: https
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL
---

#apiVersion: networking.istio.io/v1alpha3
#kind: ServiceEntry
#metadata:
#  name: github-com
#spec:
#  hosts:
#  - "github.com"
#  ports:
#  - number: 80
#    name: http
#    protocol: HTTP
#  - number: 443
#    name: https
#    protocol: HTTPS
#  resolution: DNS
#  location: MESH_EXTERNAL
