kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: coffee-shop
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /coffee-shop
        backend:
          serviceName: coffee-shop
          servicePort: 8080
---
