apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: coffee-shop
spec:
  host: coffee-shop
  subsets:
  {{- range splitList "," .subsets }}
  - name: {{ . }}
    labels:
      version: {{ . }}
  {{- end }}
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-shop-gateway
spec:
  hosts:
  - "*"
  gateways:
  - coffee-shop-gateway
  http:
  - route:
    - destination:
        host: coffee-shop
        subset: {{ .newVersion }}
        port:
          number: 8080
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: coffee-shop
spec:
  hosts:
  - coffee-shop
  http:
  - route:
    - destination:
        host: coffee-shop
        subset: {{ .newVersion }}
---
